version: "3.8"
services:
  spark-master:
    image: bitnami/spark:3.5.3
    hostname: spark-master
    container_name: spark-master
    restart: on-failure
    expose:
      - "8080"
      - "7077"
      - "6066"
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark-worker1:
    image: bitnami/spark:3.5.3
    hostname: spark-worker1
    container_name: spark-worker1
    restart: on-failure
    depends_on:
      - spark-master
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark-worker2:
    image: bitnami/spark:3.5.3
    hostname: spark-worker2
    container_name: spark-worker2
    restart: on-failure
    depends_on:
      - spark-master
    expose:
      - "8081"
    ports:
      - "8082:8081"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=0.0.0.0
      - PYSPARK_PYTHON=/usr/bin/python3.12
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  spark-network:
    driver: bridge
