version: '3'
services:
  hop:
    image: apache/hop:2.12.0
    container_name: hop
    ports:
      - 8083:8080
    volumes:
      - ./hop_files:/files
      - ./hop_data:/data
    environment:
      HOP_LOG_LEVEL: Basic
      HOP_PROJECT_FOLDER: /files/
      HOP_PROJECT_NAME: default
      HOP_RUN_CONFIG: local

  hopweb:
    image: apache/hop-web:2.12.0
    container_name: hopweb
    ports:
      - 8082:8080
    volumes:
      - ./hop_files:/files
      - ./hop_data:/data
