services:
  madlib:
    build: .
    container_name: madlib
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - madlib_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  madlib_data: {}
