version: '3'
services:
  hop:
    image: apache/hop:2.12.0
    container_name: hop
    ports:
      - 8083:8080
    environment:
      HOP_LOG_LEVEL: Basic
      HOP_PROJECT_FOLDER: /files/
      HOP_PROJECT_NAME: default
      HOP_RUN_CONFIG: local
    volumes:
      - ./hop_files:/files:rw,Z
      - ./hop_projects:/home/hop/config/projects:rw,Z

  hopweb:
    image: apache/hop-web:2.12.0
    container_name: hopweb
    ports:
      - 8082:8080
    volumes:
      - ./hop_files:/files:rw,Z
      - ./hop_projects:/usr/local/tomcat/webapps/ROOT/config/projects/default:rw,Z
