version: "3.8"
services:
  master:
    image: bitnami/spark:latest
    hostname: master
    container_name: spark-master
    restart: on-failure
    expose:
      - "4040"
      - "7077"
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=master
    networks:
      - spark-network

  worker1:
    image: bitnami/spark:latest
    hostname: worker1
    container_name: spark-worker1
    restart: on-failure
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_CORES=1
    networks:
      - spark-network

  worker2:
    image: bitnami/spark:latest
    hostname: worker2
    container_name: spark-worker2
    restart: on-failure
    expose:
      - "8082"
    ports:
      - "8082:8082"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_CORES=1
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
