version: "3.8"
services:
  master:
    #image: semantive/spark
    image: bitnami/spark
    hostname: master
    container_name: master
    restart: on-failure
    expose:
      - "4040"
      - "6066"
      - "7077"
      - "8080"
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spar
      # - PYSPARK_PYTHON=/usr/bin/python3
      # - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  worker1:
    image: bitnami/spark
    hostname: worker1
    container_name: worker1
    restart: on-failure
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - spark-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      # - PYSPARK_PYTHON=/usr/bin/python3
      # - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
    depends_on:
      - master

  # worker2:
  #   image: bitnami/spark
  #   hostname: worker2
  #   container_name: worker2
  #   expose:
  #     - "8082"
  #   ports:
  #     - "8082:8082"
  #   networks:
  #     - spark-network
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://master:7077
  #     - SPARK_WORKER_CORES=1
  #     - PYSPARK_PYTHON=/usr/bin/python3.10
  #     - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.10
  #   depends_on:
  #     - master

networks:
  # spark-network:
  #   driver: bridge
  spark-network:
    driver: overlay
  # spark-network:
  #   name: spark-network
  #   ipam:
  #     config:
  #       - subnet: 172.19.1.0/24

volumes:
  data:
